### PR TITLE
fix reply to message with sticker

### LINKED ISSUE #44: bugs stickers: reply-message does not displayed
do not see the reply-message on the jabber side, (at the same time the smiley itself is displayed)

### PR DESCRIPTION
**Pull request by Bannerets**
Resolves #44

### CODE REVIEW

File: src/bots/telegram/client.js [hunk 1]
```diff
@@ -70,9 +70,11 @@ class Message {
 class ReplyToMessage extends Message {
   static test(msg: Telegram$Message): boolean {
     const replyToMessage = msg.reply_to_message;
+
     const isReplyWithText = replyToMessage && replyToMessage.text;
+    const isReplyWithSticker = replyToMessage && replyToMessage.sticker;
 
-    return Boolean(isReplyWithText);
+    return Boolean(isReplyWithText || isReplyWithSticker);
```
Comment (ForNeVeR) [inline src/bots/telegram/client.js]: **[Discussion]** Shouldn't we just return `msg.reply_to_message` here?

**Comment by ForNeVeR** [comment]
I can't remember if we've discussed replacement of sticker emojis with `[Sticker {emoji}]` stuff. Could you please elaborate?

File: src/bots/telegram/client.js [hunk 2]
```diff
@@ -70,9 +70,11 @@ class Message {
 class ReplyToMessage extends Message {
   static test(msg: Telegram$Message): boolean {
     const replyToMessage = msg.reply_to_message;
+
     const isReplyWithText = replyToMessage && replyToMessage.text;
```
Comment (jt3k) [inline src/bots/telegram/client.js]: may-be better way is 
```javascript
const isReplyWithText = replyToMessage && 'text' in replyToMessage;
```
?
